version: '3'
services:
  util_day-app:
    container_name: api
    build: .
    command: yarn dev
    # network_mode: host
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3333/listdays/2021-01-01/usa"]
    #   interval: 10s
    #   retries: 5
    volumes:
      - .:/usr/app/
    ports:
      - 3333:3333
    expose:
      - 3333
    networks:
      - my_net

  test:
    container_name: api-test
    image: node:10
    command: bash -c "yarn && yarn test"
    # network_mode: host
    # depends_on:
    #   - util_day-app
    working_dir: /usr/app
    volumes:
      - .:/usr/app/
    links:
      - util_day-app:test-web
    networks:
      - my_net

networks:
  my_net:
