version: '3'
services:
  util_day-app:
    container_name: 'api'
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    # network_mode: host
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3333/listdays/2021-01-01/usa"]
    #   interval: 10s
    #   retries: 5
    volumes:
      - .:/usr/app/
    ports:
      - 3333:3333
    expose:
      - 3333
    networks:
      - my_net

  test:
    container_name: api-test
    image: node:10
    command: yarn test
    # network_mode: host
    depends_on:
      - util_day-app
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    links:
      - util_day-app
    networks:
      - my_net

networks:
  my_net:
    driver: bridge
