version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:

  linter:
    docker:
      - image: circleci/node:10.15.1-jessie-browsers
    steps:
      - checkout
      - run:
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run linter
          command: yarn run lint:pr -- $(git rev-list --simplify-by-decoration -1 HEAD^)

  tests:
    machine: true
    working_directory: ~/api-business-calendar
    steps:
      - checkout
      # - attach_workspace:
      #     at: ~/api-business-calendar
      # - run:
      #     command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Build and Test
          command: |
            make test
workflows:
    build_and_deploy:
      jobs:
        - linter:
            filters:
                branches:
                  only: /.*/
                tags:
                  only: /.*/
        - tests:
            requires:
              - linter
            filters:
              branches:
                only: /.*/
              tags:
                only: /.*/
